In [2]:
import tensorflow as tf
import numpy as np

In [3]:
tf.config.list_physical_devices('CPU')

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [4]:
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        tf.config.experimental.set_memory_growth(gpus[0], True)
    except RuntimeError as e:
        # 프로그램 시작시에 메모리 증가가 설정되어야만 합니다
        print(e)

In [5]:
g = tf.Graph()
with g.as_default():
    x = tf.compat.v1.placeholder(dtype=tf.float32,
                       shape=(None), name='x')
    w = tf.Variable(2.0, name='weight')
    b = tf.Variable(0.7, name='bias')

    z = w*x + b
    init = tf.compat.v1.global_variables_initializer()

## 세션을 만들고 그래프 g를 전달합니다
with tf.compat.v1.Session(graph=g) as sess:
    ## w와 b를 초기화합니다.
    sess.run(init)
    ## z를 평가합니다.
    for t in [1.0, 0.6, -1.8]:
        print('x=%4.1f --> z=%4.1f'%(
              t, sess.run(z, feed_dict={x:t})))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
x= 1.0 --> z= 2.7
x= 0.6 --> z= 1.9
x=-1.8 --> z=-2.9


In [6]:
w = tf.Variable(2.0, name='weight')
b = tf.Variable(0.7, name='bias')

# z를 평가합니다.
for x in [1.0, 0.6, -1.8]:
    z = w * x + b
    print('x=%4.1f --> z=%4.1f'%(x, z))

x= 1.0 --> z= 2.7
x= 0.6 --> z= 1.9
x=-1.8 --> z=-2.9


In [7]:
t1 = tf.constant(np.pi)
t2 = tf.constant([1,2,3,4])
t3 = tf.constant([[1,2], [3,4]])

In [8]:
r1 = tf.rank(t1)
r2 = tf.rank(t2)
r3 = tf.rank(t3)

s1 = t1.get_shape()
s2 = t2.get_shape()
s3 = t3.get_shape()

In [9]:
print('크기', s1, s2, s3)

크기 () (4,) (2, 2)


In [10]:
print('랭크', r1, r2, r3)

랭크 tf.Tensor(0, shape=(), dtype=int32) tf.Tensor(1, shape=(), dtype=int32) tf.Tensor(2, shape=(), dtype=int32)


In [11]:
arr = np.array([[1.,2.,3.,3.5],
                [4.,5.,6.,6.5],
                [7.,8.,9.,9.5]])

T1 = tf.constant(arr)

In [12]:
print(T1)

tf.Tensor(
[[1.  2.  3.  3.5]
 [4.  5.  6.  6.5]
 [7.  8.  9.  9.5]], shape=(3, 4), dtype=float64)


In [13]:
s = T1.get_shape()

In [14]:
print('T1의 크기: ', s)
print('T1의 크기: ', T1.shape)

T1의 크기:  (3, 4)
T1의 크기:  (3, 4)


In [15]:
T2 = tf.Variable(np.random.normal(size=s))

In [16]:
print(T2)

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float64, numpy=
array([[-0.02620816, -0.27432914, -0.75751709, -0.16555636],
       [ 1.71663404, -0.95663951,  1.09510525,  0.87629203],
       [ 0.48070581, -0.40209889,  0.27773914, -0.74943567]])>


In [18]:
T3 = tf.Variable(np.random.normal(size=s[0]))

In [19]:
print(T3)

<tf.Variable 'Variable:0' shape=(3,) dtype=float64, numpy=array([ 0.77319656, -0.09086768,  0.28365312])>


In [20]:
T4 = tf.reshape(T1, shape=[1,1,-1])

In [21]:
print(T4)

tf.Tensor([[[1.  2.  3.  3.5 4.  5.  6.  6.5 7.  8.  9.  9.5]]], shape=(1, 1, 12), dtype=float64)


In [22]:
T5 = tf.reshape(T1, shape=[1,3,-1])

In [23]:
print(T5)

tf.Tensor(
[[[1.  2.  3.  3.5]
  [4.  5.  6.  6.5]
  [7.  8.  9.  9.5]]], shape=(1, 3, 4), dtype=float64)


In [31]:
T6 = tf.transpose(T5, perm=[2, 1, 0])
print(T6)

tf.Tensor(
[[[1. ]
  [4. ]
  [7. ]]

 [[2. ]
  [5. ]
  [8. ]]

 [[3. ]
  [6. ]
  [9. ]]

 [[3.5]
  [6.5]
  [9.5]]], shape=(4, 3, 1), dtype=float64)


In [30]:
T7 = tf.transpose(T5, perm=[0, 2, 1])
print(T7)

tf.Tensor(
[[[1.  4.  7. ]
  [2.  5.  8. ]
  [3.  6.  9. ]
  [3.5 6.5 9.5]]], shape=(1, 4, 3), dtype=float64)


In [32]:
T8 = tf.transpose(T5, perm=[2, 0, 1])
print(T8)

tf.Tensor(
[[[1.  4.  7. ]]

 [[2.  5.  8. ]]

 [[3.  6.  9. ]]

 [[3.5 6.5 9.5]]], shape=(4, 1, 3), dtype=float64)


In [36]:
T5_splt = tf.split(T5, num_or_size_splits=2, axis=2)

In [37]:
print(T5_splt)

[<tf.Tensor: shape=(1, 3, 2), dtype=float64, numpy=
array([[[1., 2.],
        [4., 5.],
        [7., 8.]]])>, <tf.Tensor: shape=(1, 3, 2), dtype=float64, numpy=
array([[[3. , 3.5],
        [6. , 6.5],
        [9. , 9.5]]])>]


In [38]:
t1 = tf.ones(shape=(5,1), dtype=tf.float32)
t2 = tf.zeros(shape=(5,1), dtype=tf.float32)

In [39]:
print(t1)
print(t2)

tf.Tensor(
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]], shape=(5, 1), dtype=float32)
tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(5, 1), dtype=float32)


In [40]:
t3 = tf.concat([t1, t2], axis=0)
t4 = tf.concat([t1, t2], axis=1)

In [41]:
print(t3)
print(t4)

tf.Tensor(
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(10, 1), dtype=float32)
tf.Tensor(
[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]], shape=(5, 2), dtype=float32)
